registrarCategoria('animales', {
    nombre: '🦁 Animales',
    palabras: [
        "Jirafa", "Elefante", "Pingüino", "León", "Tiburón", 
        "Canguro", "Panda", "Koala", "Gallina", "Dinosaurio",
        "Murciélago", "Serpiente", "Gorila", "Mosquito", "Ballena",
        "Ornitorrinco", "Camaleón", "Perezoso", "Hipopótamo", "Lobo",
        "Águila", "Delfín", "Pulpo", "Cebra", "Rinoceronte",
        "Tigre", "Zorro", "Búho", "Rata", "Tortuga",
        "Salmón", "Vaca", "Caballo", "Conejo", "Gato",
        "Perro", "Oso", "Hiena", "Abeja", "Cangrejo",
        "Loro", "Leopardo", "Mariposa", "Rana", "Guepardo",
        "Coyote", "Halcón", "Alce", "Bisonte", "Búfalo",
        "Ciervo", "Langosta", "Cabra", "Llamas", "Zorro ártico",
        "Pavo real", "Oso polar", "Avestruz", "Sapo", "Pavo",
        "Caracol", "Hombre de Neanderthal", "Pollo", "Jabalí", "Peces",
        "Cigüeña", "Araña", "Pato", "Gaviota", "Tejón",
        "Halcón peregrino", "Perro bulldog", "Erizo", "Liebre", "Ardilla",
        "Gaviota", "Pingüino", "Tiburón blanco", "Águila pescadora", "Pelícano",
        "Camarón", "Peces tropicales", "Tejón", "Halcón de cola roja", "Ciervo de cola blanca",
        "Gato de monte", "Perro de montaña", "Puma", "Mapache", "Ratón",
        "León de montaña", "Robalo", "Lombriz", "Pececillo", "León marino",
        "Tortuga marina", "Cangrejo ermitaño", "Nutria", "Lince", "Búfalo de agua",
        "Perro pastor", "Lémur", "Cebra de llanura", "Murciélago frugívoro", "Gato de las cavernas",
        "Búho real", "Robalo de río", "Cebra de montaña", "Cangrejo de mar", "Búho nival",
        "Oso grizzly", "Pingüino de Humboldt", "Perro golden retriever", "Pez ángel", "Águila calva",
        "Tigre blanco", "Nutria marina", "Gato callejero", "Mariposa monarca", "Gato bobtail",
        "Serpiente de coral", "Tiburón ballena", "León marino", "Caimán", "Caballo andaluz",
        "Dragón barbudo", "Caballo salvaje", "Gorila de montaña", "Águila de paso", "Perro San Bernardo",
        "Corzo", "Bisonte americano", "Gato persa", "Tejón", "Lince rojo", "Gato montés",
        "Guepardo", "Vaca lechera", "Cebra del Cabo", "Caracol de jardín", "Lince ibérico",
        "Jabalí", "Ardilla de cola roja", "Loro australiano", "Perro salchicha", "Gato siamés",
        "León africano", "Tigre bengala", "Zorro plateado", "Gorila occidental", "Búho chico",
        "Avestruces", "Pelícano blanco", "Búho de orejas largas", "Caracol de tierra", "Cangrejo de río",
        "Jirafa africana", "Bisonte europeo", "Cebra de Grévy", "Robalo de mar", "Iguana verde",
        "Peces dorados", "Serpiente constrictora", "Oso panda", "Pavo salvaje", "Gato de campo",
        "Albatros", "Peces de agua dulce", "Perro terrier", "Gato esfinge", "Tigre de Sumatra",
        "Gato manso", "Pececillos tropicales", "Tiburón martillo", "Pingüino emperador", "Robalo de mar",
        "Conejo europeo", "Dromedario", "León blanco", "Gato leopardo", "Cebra de las llanuras"
    ]
});